export default {
  TWITTER: 'TWITTER',
  MATCH: 'MATCH',
  MESSAGES: 'MESSAGES',
  NOTES: 'NOTES',
  MARKETPLACE: 'MARKETPLACE',
  CONTACTS: 'CONTACTS',
  CAMERA: 'CAMERA',
  PHONE: 'PHONE',
  GARAGE: 'GARAGE',
  MAIL: 'MAIL',
  HOUSE: 'HOUSE'
};
